services:
  db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - db:/var/lib/mysql
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    
  tms:
    depends_on:
      - db
      - rabbitmq
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_PORT:$SPRING_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/tms?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.open-in-view":"false",
        "spring.rabbitmq.host" : "rabbitmq",
        "spring.rabbitmq.username" : "guest",
        "spring.rabbitmq.password" : "guest",
        "spring.rabbitmq.port" : "15672",
        "spring.rabbitmq.exchange" : "user.exchange",
        "spring.rabbitmq.queue" : "user.queue",
        "spring.rabbitmq.routingkey" : "user.routingkey"
      }'
    stdin_open: true
    tty: true
volumes:
  db: